### ISSUE TITLE
dont know how to configure nvimux to use neoterm

### ISSUE THREAD

**Issue by maple-leaf** [Vigemus/nvimux#29]
try setting `let g:nvimux_quickterm_provider = 'neoterm#new'` with no lucks.

**Comment by hkupty** [comment]
Hum.. That is a bad sign that I've left the docs a mess.

I'll deprecate the VimL config in favor of lua only, so I'd recommend switching to it, but the property you're looking for is `quickterm_command` (`g:nvimux_quickterm_command` in VimL).

I'll leave this open as sign for me to fix the docs ASAP.

**Comment by hkupty** [comment]
Maybe this is already fixed with the lua code, though the documentation is still poor. Should I close it?

**Comment by maple-leaf** [comment]
It seems work well now. Close this.
