### ISSUE TITLE
Lua snippet errors on reload of init.vim

### ISSUE THREAD

**Issue by wreed4** [Vigemus/nvimux#31]
Hello again!  It seems the lua configuration is not idempotent.  Reloading my vimrc is a frequent workflow of mine since I add or change mappings frequently (perhaps too frequently.. but details).  My current configuration is _almost_ exactly what's in the docs.

```lua
lua << EOF
local nvimux = require('nvimux')

-- Nvimux configuration
nvimux.config.set_all{
  prefix = '<C-a>',
  new_window = 'term', -- Use 'term' if you want to open a new term for every new window
  new_tab = nil, -- Defaults to new_window. Set to 'term' if you want a new term for every new tab
  new_window_buffer = 'single',
  quickterm_direction = 'botright',
  quickterm_orientation = 'vertical',
  quickterm_scope = 't', -- Use 'g' for global quickterm
  quickterm_size = '80',
}

-- Nvimux custom bindings
nvimux.bindings.bind_all{
  {'-', ':NvimuxHorizontalSplit', {'n', 'v', 'i', 't'}},
  {'\\|', ':NvimuxVerticalSplit', {'n', 'v', 'i', 't'}},
}

-- Required so nvimux sets the mappings correctly
nvimux.bootstrap()
EOF
```

When I re-source my vimrc from within a running instance, I get the following error:
```
Error detected while processing /home/william/.dotfiles/vim/vimrc:
line  551:
E5105: Error while calling lua chunk: /home/william/.vim/bundle/nvimux//lua/nvimux.lua:112: bad argument #1 to 'sub' (string expected, got nil)
```

Thanks again in advance!

**Comment by hkupty** [comment]
Hum... This is interesting. I'll take a look. What I'd advise you, in the meantime, is to avoid bootstrapping a second time. I'll try to debug with your config and I'll let you know once I find something.

Cheers,
Henry Kupty

**Comment by wreed4** [comment]
Is there a way to only run that line once in my init.vim? I don't know of one.

**Comment by hkupty** [comment]
Hum.. I thought about adding an `if` in your lua code so you don't run into this error. Not sure about VimL though.

The good thing is that I was able to reproduce the error, so clearly bootstrap is not idempotent - it happens if you call it twice in a row as well.

**Comment by wreed4** [comment]
What would the condition be? I can do the condition just around the bootstrap in the lua section or around the whole part in VimL if possible. But if there's something I can check just around the bootstrap line for now, that'd at least be an improvement.

**Comment by hkupty** [comment]
Sorry for taking long to answer.
I just tested this and it works:
```lua
if nvimux_loaded == nil then
  nvimux.bootstrap()
end
nvimux_loaded = true
```

**Comment by hkupty** [comment]
Hi. 

Is this issue still valid? 
Should I close it?

Cheers,
Henry

**Comment by wreed4** [comment]
The condition works well, sorry for not updating.  Is the bootstrap idempotent yet? or is the condition just the right way to do this?

**Comment by hkupty** [comment]
I just pushed something that moves makes the check not required on your side. I've checked that the error still persists, but you wouldn't have issues with that by your usage workflow.
